# Site settings
title: Wind and Waves
email: riley787cmplex@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ethanriley.github.io/" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
published: true


sass:
  sass_dir: _sass
  style: compressed


include: ['_pages', '_static', '_scripts']

collections:
  news:
    output: true
  products:
    output: true
    permalink: /shop/products/:path.html
    images:
      output: true
      permalink: /shop/products/images/:path

# Build settings
markdown: kramdown
